-- ICR Meal Dashboard v1.1 beta
-- Run once in the Supabase SQL Editor.

create table if not exists public.meal_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id text not null,
  timestamp timestamptz not null default now(),
  meal_name text,
  meal_type text,
  fat_level text,
  fat_grams numeric,
  carbs numeric not null,
  bg numeric not null,
  icr numeric not null,
  target numeric not null default 8,
  calculated_dose numeric not null,
  actual_insulin numeric,
  bolus_timing text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, client_id)
);

alter table public.meal_entries enable row level security;

drop policy if exists "Users can read own meal entries" on public.meal_entries;
drop policy if exists "Users can insert own meal entries" on public.meal_entries;
drop policy if exists "Users can update own meal entries" on public.meal_entries;
drop policy if exists "Users can delete own meal entries" on public.meal_entries;

create policy "Users can read own meal entries"
on public.meal_entries for select
using (auth.uid() = user_id);

create policy "Users can insert own meal entries"
on public.meal_entries for insert
with check (auth.uid() = user_id);

create policy "Users can update own meal entries"
on public.meal_entries for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own meal entries"
on public.meal_entries for delete
using (auth.uid() = user_id);

create index if not exists meal_entries_user_timestamp_idx
on public.meal_entries (user_id, timestamp desc);
