from pathlib import Path

p=Path('index.html')
s=p.read_text()
s=s.replace('<title>ICR Meal Dashboard v2.6.2</title>','<title>ICR Meal Dashboard v2.7.0</title>')
s=s.replace('<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script>','<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script>\n<script src="restaurant_foods_v2.7.0.js"></script>')
s=s.replace('v2.6.2</small></h1>','v2.7.0</small></h1>')
s=s.replace('<div class="badge">v2.6.2 LIVE</div>','<div class="badge">v2.7.0 LIVE</div>')
css='''.restaurantPanel{margin-top:12px;border:1px solid #b9d8ff;background:linear-gradient(180deg,#f5faff,#fff);border-radius:16px;padding:14px}.restaurantChains{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:11px}.restaurantChain{border:1px solid var(--line);background:#fff;color:var(--ink);padding:13px;border-radius:13px;text-align:left}.restaurantChain strong{display:block;font-size:1rem}.restaurantChain span{display:block;color:var(--muted);font-size:.72rem;margin-top:3px}.restaurantChain.active{background:var(--blue);color:#fff;border-color:var(--blue)}.restaurantChain.active span{color:#eaf3ff}.restaurantTools{display:flex;gap:8px;align-items:end;flex-wrap:wrap;margin-top:12px}.restaurantTools>div{flex:1;min-width:180px}.restaurantCats{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.restaurantCat{background:#edf2f7;color:#344054;padding:7px 10px;font-size:.76rem}.restaurantCat.active{background:#dbeafe;color:#0b5cab}.restaurantResults{display:grid;grid-template-columns:repeat(2,1fr);gap:9px;margin-top:10px}.restaurantItem{border:1px solid var(--line);border-radius:14px;padding:12px;background:#fff}.restaurantItemHead{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.restaurantBrand{font-size:.7rem;font-weight:850;color:var(--blue);text-transform:uppercase;letter-spacing:.04em}.restaurantMacros{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:10px}.restaurantMacro{background:#f8fafc;border-radius:9px;padding:7px;text-align:center}.restaurantMacro span{display:block;font-size:.64rem;color:var(--muted)}.restaurantMacro strong{font-size:.9rem}.restaurantSource{font-size:.67rem;color:var(--muted);line-height:1.35;margin-top:8px}.restaurantUse{width:100%;margin-top:10px}.restaurantDisclaimer{font-size:.72rem;color:#475467;line-height:1.4;margin-top:10px;padding:9px 10px;background:#f8fafc;border-radius:10px}.restaurantClose{white-space:nowrap}\n'''
s=s.replace('@media(max-width:800px){','@media(max-width:800px){.restaurantResults{grid-template-columns:1fr}.restaurantChains{grid-template-columns:1fr 1fr 1fr}.restaurantMacros{grid-template-columns:repeat(4,1fr)}')
s=s.replace('.intelligenceGrid{display:grid;',css+'.intelligenceGrid{display:grid;')
old='<div class="smartGrid"><button id="barcodeMode" class="smartAction" type="button"><strong>Scan barcode</strong><span>Camera or manual EAN/UPC lookup</span></button><button id="labelMode" class="smartAction" type="button"><strong>Scan nutrition label</strong><span>Photo OCR with manual confirmation</span></button><button id="manualMode" class="smartAction" type="button"><strong>Manual nutrition</strong><span>Enter per-100g values yourself</span></button></div></div>'
new='<div class="smartGrid"><button id="barcodeMode" class="smartAction" type="button"><strong>Scan barcode</strong><span>Camera or manual EAN/UPC lookup</span></button><button id="labelMode" class="smartAction" type="button"><strong>Scan nutrition label</strong><span>Photo OCR with manual confirmation</span></button><button id="manualMode" class="smartAction" type="button"><strong>Manual nutrition</strong><span>Enter per-100g values yourself</span></button><button id="restaurantMode" class="smartAction" type="button"><strong>Restaurant food</strong><span>Greggs, PizzaExpress & McDonald\'s UK</span></button></div></div>'
assert old in s, 'Smart Food action block not found'
s=s.replace(old,new)
anchor='<div id="foodCloudState" class="notice warn">Food library cloud status: checking...</div>'
panel='''<div id="restaurantPanel" class="restaurantPanel hidden"><div class="reviewHead"><div><h3 style="margin:0">Restaurant food</h3><div class="sectionNote">Choose a restaurant, then tap the item you ate. Portion nutrition is copied straight into your meal.</div></div><button id="closeRestaurant" class="secondary restaurantClose" type="button">Close</button></div><div id="restaurantChains" class="restaurantChains"></div><div class="restaurantTools"><div><label for="restaurantSearch">Search menu</label><input id="restaurantSearch" placeholder="Search selected restaurant"></div></div><div id="restaurantCats" class="restaurantCats"></div><div id="restaurantResults" class="restaurantResults"></div><div class="restaurantDisclaimer">Restaurant recipes and portions can change. Each entry keeps its nutrition source and source date so you can see how current it is. If an item has changed, check the restaurant before relying on an old entry.</div></div>'''
assert anchor in s, 'Food cloud state block not found'
s=s.replace(anchor,anchor+'\n'+panel)
marker='function smartMode(mode){'
funcs=r'''let restaurantSelected='Greggs',restaurantCategory='All';
function restaurantFoods(){return Array.isArray(window.RESTAURANT_FOODS_V270)?window.RESTAURANT_FOODS_V270:[]}
function openRestaurantBrowser(){$('smartPanel').classList.add('hidden');$('restaurantPanel').classList.remove('hidden');renderRestaurantBrowser();$('restaurantPanel').scrollIntoView({behavior:'smooth',block:'start'})}
function renderRestaurantBrowser(){const all=restaurantFoods(),restaurants=[...new Set(all.map(x=>x.restaurant))];if(!restaurants.includes(restaurantSelected))restaurantSelected=restaurants[0]||'';$('restaurantChains').innerHTML=restaurants.map(r=>{const n=all.filter(x=>x.restaurant===r).length;return `<button class="restaurantChain ${r===restaurantSelected?'active':''}" data-r="${esc(r)}" type="button"><strong>${esc(r)}</strong><span>${n} menu item${n===1?'':'s'}</span></button>`}).join('');document.querySelectorAll('.restaurantChain').forEach(b=>b.onclick=()=>{restaurantSelected=b.dataset.r;restaurantCategory='All';$('restaurantSearch').value='';renderRestaurantBrowser()});const base=all.filter(x=>x.restaurant===restaurantSelected),cats=['All',...new Set(base.map(x=>x.category))];if(!cats.includes(restaurantCategory))restaurantCategory='All';$('restaurantCats').innerHTML=cats.map(c=>`<button class="restaurantCat ${c===restaurantCategory?'active':''}" data-c="${esc(c)}" type="button">${esc(c)}</button>`).join('');document.querySelectorAll('.restaurantCat').forEach(b=>b.onclick=()=>{restaurantCategory=b.dataset.c;renderRestaurantResults()});renderRestaurantResults()}
function renderRestaurantResults(){const term=($('restaurantSearch')?.value||'').trim().toLowerCase();let list=restaurantFoods().filter(x=>x.restaurant===restaurantSelected&&(restaurantCategory==='All'||x.category===restaurantCategory));if(term)list=list.filter(x=>(x.name+' '+x.category).toLowerCase().includes(term));$('restaurantResults').innerHTML=list.map((x,i)=>`<div class="restaurantItem"><div class="restaurantItemHead"><div><div class="restaurantBrand">${esc(x.restaurant)} · ${esc(x.category)}</div><strong>${esc(x.name)}</strong><div class="foodMeta">${esc(x.portion)}</div></div><span class="pill">${x.evidence==='official'?'OFFICIAL':'CHECKED'}</span></div><div class="restaurantMacros"><div class="restaurantMacro"><span>Carbs</span><strong>${Number(x.carbs).toFixed(x.carbs%1?1:0)}g</strong></div><div class="restaurantMacro"><span>Fat</span><strong>${Number(x.fat).toFixed(x.fat%1?1:0)}g</strong></div><div class="restaurantMacro"><span>Protein</span><strong>${Number(x.protein).toFixed(x.protein%1?1:0)}g</strong></div><div class="restaurantMacro"><span>kcal</span><strong>${Number(x.kcal).toFixed(0)}</strong></div></div><div class="restaurantSource">${esc(x.source)} · source ${esc(x.sourceDate)}</div><button class="primary restaurantUse" data-i="${i}" type="button">Use this item</button></div>`).join('')||'<div class="sectionNote">No matching menu items yet.</div>';document.querySelectorAll('.restaurantUse').forEach(b=>b.onclick=()=>useRestaurantFood(list[Number(b.dataset.i)]))}
function useRestaurantFood(x){if(!x)return;$('mealName').value=`${x.restaurant} - ${x.name}`;$('carbs').value=Number(x.carbs);$('fatGrams').value=Number(x.fat);const mt=$('mealType');if([...mt.options].some(o=>o.text===x.mealType))mt.value=x.mealType;syncFat();actualEdited=false;updateDose();const tag=`Restaurant nutrition: ${x.source}; source ${x.sourceDate}; ${x.portion}`;const existing=$('notes').value.trim();$('notes').value=existing?`${existing} | ${tag}`:tag;$('restaurantPanel').classList.add('hidden');$('mealForm').closest('section')?.scrollIntoView({behavior:'smooth',block:'start'});setNotice(`${x.restaurant} ${x.name}: ${x.carbs}g carbs and ${x.fat}g fat copied into the meal. Check the portion, then complete the live CGM and insulin fields.`,'good')}
'''
assert marker in s, 'smartMode not found'
s=s.replace(marker,funcs+marker)
bind="$('barcodeMode').onclick=()=>smartMode('barcode');$('labelMode').onclick=()=>smartMode('label');$('manualMode').onclick=()=>smartMode('manual');"
assert bind in s, 'Smart Food event bindings not found'
s=s.replace(bind,bind+"$('restaurantMode').onclick=openRestaurantBrowser;$('closeRestaurant').onclick=()=>$('restaurantPanel').classList.add('hidden');$('restaurantSearch').addEventListener('input',renderRestaurantResults);")
p.write_text(s)

readme=Path('README.md').read_text()
readme=readme.replace('v2.6.2','v2.7.0')
readme+='''\n\n## Restaurant Foods (v2.7.0)\nSmart Food now includes a separate UK restaurant browser. The starter database covers Greggs, PizzaExpress and McDonald's. Choose a chain, filter/search the menu and use an item to prefill the meal description, carbohydrate, fat and meal type. Restaurant records keep source and source-date metadata and remain separate from the personal cloud food library. Add future chains by extending `restaurant_foods_v2.7.0.js`.\n'''
Path('README.md').write_text(readme)

ch=Path('CHANGELOG.md').read_text()
entry='''# v2.7.0 - Restaurant Foods\n- Added a clean mobile restaurant-food browser inside Smart Food.\n- Starter UK chains: Greggs, PizzaExpress and McDonald's.\n- Added restaurant and category filters plus menu search.\n- Restaurant item cards show portion carbs, fat, protein, kcal, source and source date.\n- One tap copies meal description, carbs, fat and suggested meal type into Add meal.\n- Restaurant nutrition is kept in a separate versioned dataset so future chains can be added without bloating the personal food library.\n- No change to ICR, dose calculation, Nightscout or CGM intelligence logic.\n\n'''
Path('CHANGELOG.md').write_text(entry+ch)

brain=Path('PROJECT_BRAIN.md').read_text()
brain+='''\n\n## v2.7.0 Restaurant Foods\n- Smart Food has a separate restaurant browser designed for an expanding UK chain database.\n- Initial chains: Greggs, PizzaExpress and McDonald's.\n- Restaurant data lives in `restaurant_foods_v2.7.0.js`, separate from the user's personal Supabase food library.\n- Every restaurant item records portion nutrition plus provenance/source date.\n- New chains should be added to the versioned restaurant dataset and surfaced automatically by the existing browser.\n- Using an item fills meal name, carbs, fat and meal type, while the user still confirms the actual meal and insulin details.\n'''
Path('PROJECT_BRAIN.md').write_text(brain)
