from pathlib import Path
import re

p=Path('index.html')
s=p.read_text(encoding='utf-8')

progress_pattern=re.compile(r'<section class="card"><h2>My CGM progress</h2>.*?</section>\s*<section class="card"><h2>Clinical goals</h2>.*?</section>',re.S)
progress='''<section class="card"><h2>My CGM progress</h2><div class="progressGrid"><div class="snapshot"><strong>Latest review - 27 Sep 2026</strong><div class="signalGrid" style="margin-top:10px"><div class="signal"><span>Time in range</span><strong>84.5%</strong></div><div class="signal"><span>Average glucose</span><strong>7.78</strong></div><div class="signal"><span>GMI</span><strong>6.66%</strong></div><div class="signal"><span>CV</span><strong>27.1%</strong></div></div><div class="reassure"><strong>Coach summary:</strong> Current 14-day control remains strong and consistent: TIR 84.5%, average glucose 7.78 mmol/L, GMI 6.66% and CV 27.1%. Time below 3.9 is 1.5%, below 3.0 is 0.26%, above 10 is 14.0% and above 13.9 is 0.26%. The most recent 7 days are very similar, so the 14-day result is not being propped up by an unusually good earlier week. <strong>ICR verdict:</strong> 1:15 remains the best-supported working baseline. The clean meal evidence does not support tightening the ratio globally.</div></div><div><div class="learning good"><strong>What is working</strong><br>TIR remains well above the 70% goal, GMI remains below 7% and CV is comfortably below 36%. In clean assessable meal windows, 79% were at or below 10 mmol/L at two hours and none fell below 3.9 mmol/L.</div><div class="learning watch"><strong>What to watch</strong><br>Some foods still show a delayed-rise pattern, including Shin Ramyun, pasty, crisps and mixed/high-fat meals. These are more useful as meal-type and timing clues than evidence that 1:15 is globally wrong.</div><div class="learning info"><strong>Data quality</strong><br>The app export contains 94 logged meals plus 8 context events from 24 Aug to 27 Sep. The current Clarity file contains 3,865 CGM readings from 14 to 27 Sep. There are 37 logged meals in the current Clarity window. Context events, missed insulin, untracked food and overlapping eating are excluded from clean ICR evidence.</div></div></div></section>
<section class="card"><h2>Clinical goals</h2><div class="goalGrid"><div class="goalItem"><div><strong>Time in range</strong><div class="goalMeta">Goal &gt;70% | Latest 84.5%</div></div><span class="tick">ACHIEVED</span></div><div class="goalItem"><div><strong>CV</strong><div class="goalMeta">Goal &lt;36% | Latest 27.1%</div></div><span class="tick">ACHIEVED</span></div><div class="goalItem"><div><strong>GMI</strong><div class="goalMeta">Goal &lt;7% | Latest 6.66%</div></div><span class="tick">ACHIEVED</span></div></div></section>'''
s,n=progress_pattern.subn(progress,s,count=1)
if n!=1: raise SystemExit(f'progress replacement count {n}')

learn_pattern=re.compile(r'<section class="card"><h2>What I\'ve learned about Darren\'s diabetes</h2>.*?</section>',re.S)
learn='''<section class="card"><h2>What I've learned about Darren's diabetes</h2><div class="learnGrid"><div class="learnItem"><span class="evidence ev-proven">PROVEN REPEATEDLY</span><strong>Time in range remains well above the 70% goal and glucose variability remains comfortably below the 36% target.</strong></div><div class="learnItem"><span class="evidence ev-likely">LIKELY</span><strong>1:15 remains the best-supported working ICR. In the current clean meal evidence there is no repeated post-meal low pattern supporting a weaker ratio, and the data does not justify tightening it globally.</strong></div><div class="learnItem"><span class="evidence ev-likely">LIKELY</span><strong>Meal composition and delayed absorption explain more of the poorer excursions than a consistent global ICR problem. Shin Ramyun, pasty, crisps and mixed/high-fat meals remain useful examples to watch.</strong></div><div class="learnItem"><span class="evidence ev-investigate">UNDER INVESTIGATION</span><strong>Meal-specific timing may matter, especially for rapid-starch and higher-fat foods, but the evidence is not clean enough for a single pre-bolus timing rule.</strong></div><div class="learnItem"><span class="evidence ev-rule">ANALYSIS RULE</span><strong>Context-only events, missed insulin and untracked food explain glucose but are excluded from clean ICR evidence.</strong></div><div class="learnItem"><span class="evidence ev-rule">ANALYSIS RULE</span><strong>Closely spaced foods are grouped before judging outcomes, and meals without enough clean CGM follow-up are not used to judge the ratio.</strong></div></div></section>'''
s,n=learn_pattern.subn(learn,s,count=1)
if n!=1: raise SystemExit(f'learn replacement count {n}')

timeline_pattern=re.compile(r'<section class="card"><h2>Review timeline - last 5 uploads</h2>.*?</section>',re.S)
timeline='''<section class="card"><h2>Review timeline - last 5 uploads</h2><div class="timeline"><div class="review"><div class="reviewDate">27 Sep 2026</div><div class="reviewMetrics"><span class="chip">TIR 84.5%</span><span class="chip">Avg 7.78</span><span class="chip">GMI 6.66%</span><span class="chip">CV 27.1%</span></div></div><div class="review"><div class="reviewDate">11 Sep 2026</div><div class="reviewMetrics"><span class="chip">TIR 86%</span><span class="chip">Avg 7.6</span><span class="chip">GMI 6.6%</span><span class="chip">CV 30.0%</span></div></div><div class="review"><div class="reviewDate">8 Sep 2026</div><div class="reviewMetrics"><span class="chip">TIR 85%</span><span class="chip">Avg 7.6</span><span class="chip">GMI 6.6%</span><span class="chip">CV 30.4%</span></div></div><div class="review"><div class="reviewDate">6 Sep 2026</div><div class="reviewMetrics"><span class="chip">TIR 84%</span><span class="chip">Avg 7.7</span><span class="chip">GMI 6.6%</span><span class="chip">CV 29.9%</span></div></div><div class="review"><div class="reviewDate">2 Sep 2026</div><div class="reviewMetrics"><span class="chip">TIR 85%</span><span class="chip">Avg 7.7</span><span class="chip">GMI 6.6%</span><span class="chip">CV 28.8%</span></div></div></div></section>'''
s,n=timeline_pattern.subn(timeline,s,count=1)
if n!=1: raise SystemExit(f'timeline replacement count {n}')

protocol_pattern=re.compile(r'<section class="card"><h2>3-file review protocol</h2>.*?</section>',re.S)
protocol='''<section class="card"><h2>CGM review protocol</h2><div class="protocolBox"><strong>Current standard review uses 2 files:</strong><br>1. Dexcom Clarity raw CSV<br>2. ICR Meal Dashboard CSV<br><br>The Clarity PDF is optional and only needed if a CSV result needs checking against Dexcom's own report calculations.</div></section>'''
s,n=protocol_pattern.subn(protocol,s,count=1)
if n!=1: raise SystemExit(f'protocol replacement count {n}')

marker='<div class="versionGrid">'
item='''<div class="versionGrid"><div class="versionItem"><strong>27 Sep 2026 - CGM review</strong><ul><li>Updated CGM Progress to TIR 84.5%, average 7.78 mmol/L, GMI 6.66% and CV 27.1%.</li><li>Recorded TBR below 3.9 at 1.5%, below 3.0 at 0.26%, TAR above 10 at 14.0% and above 13.9 at 0.26%.</li><li>Retained 1:15 as the evidence-supported working ICR; 79% of clean assessable meals were at or below 10 mmol/L at two hours and none fell below 3.9 mmol/L.</li><li>Updated the review protocol so the app export plus Clarity CSV are the standard review set; the Clarity PDF is optional for cross-checking.</li><li>No insulin calculation, correction-dose or Nightscout automation logic changed.</li></ul></div>'''
if marker in s and '27 Sep 2026 - CGM review' not in s:
    s=s.replace(marker,item,1)

p.write_text(s,encoding='utf-8')
