from pathlib import Path
import re

p=Path('index.html')
s=p.read_text(encoding='utf-8')

progress_pattern=re.compile(r'<section class="card"><h2>My CGM progress</h2>.*?</section>\s*<section class="card"><h2>Clinical goals</h2>.*?</section>',re.S)
progress='''<section class="card"><h2>My CGM progress</h2><div class="progressGrid"><div class="snapshot"><strong>Latest review - 11 Sep 2026</strong><div class="signalGrid" style="margin-top:10px"><div class="signal"><span>Time in range</span><strong>86%</strong></div><div class="signal"><span>Average glucose</span><strong>7.6</strong></div><div class="signal"><span>GMI</span><strong>6.6%</strong></div><div class="signal"><span>CV</span><strong>30.0%</strong></div></div><div class="reassure"><strong>Coach summary:</strong> TIR has improved to 86%, average glucose remains 7.6 mmol/L, GMI remains 6.6% and CV is 30.0%. The current 14-day window records 0% low and 0% very low, and all headline AGP goals remain achieved. <strong>ICR verdict:</strong> 1:15 remains the best-supported working baseline. The newer evidence still does not show a repeated low pattern suggesting the global ratio is too strong. The main watch area remains meal-specific excursions, uncertain/untracked food, overlapping eating and delayed high-fat/high-carb responses.</div></div><div><div class="learning good"><strong>What is working</strong><br>TIR is 86%, GMI 6.6% and CV 30.0%, all inside the AGP goals. The latest 14-day window records 0% low and 0% very low. Recent meals close to 1:15 continue to provide useful evidence without a repeated post-meal low signal.</div><div class="learning watch"><strong>What to watch</strong><br>The 10 Sep pub pie-and-mash episode is context-only because the carbs and dose decision were uncertain, so it must not distort the ICR calculation. High-fat/high-carb meals such as the later PizzaExpress meal still need the full delayed trace rather than a short snapshot.</div><div class="learning info"><strong>Data quality</strong><br>The app remains the primary meal-context record and Dexcom is used for corroboration and glucose outcomes. Context-only untracked food is excluded from clean ICR evidence, closely spaced eating is grouped, and meals logged too recently for a full outcome are carried into the next review.</div></div></div></section>
<section class="card"><h2>Clinical goals</h2><div class="goalGrid"><div class="goalItem"><div><strong>Time in range</strong><div class="goalMeta">Goal &gt;70% | Latest 86%</div></div><span class="tick">ACHIEVED</span></div><div class="goalItem"><div><strong>CV</strong><div class="goalMeta">Goal &lt;36% | Latest 30.0%</div></div><span class="tick">ACHIEVED</span></div><div class="goalItem"><div><strong>GMI</strong><div class="goalMeta">Goal &lt;7% | Latest 6.6%</div></div><span class="tick">ACHIEVED</span></div></div></section>'''
s,n=progress_pattern.subn(progress,s,count=1)
if n!=1: raise SystemExit(f'progress replacement count {n}')

learn_pattern=re.compile(r'<section class="card"><h2>What I\'ve learned about Darren\'s diabetes</h2>.*?</section>',re.S)
learn='''<section class="card"><h2>What I've learned about Darren's diabetes</h2><div class="learnGrid"><div class="learnItem"><span class="evidence ev-proven">PROVEN REPEATEDLY</span><strong>Time in range remains well above the 70% goal across recent reviews.</strong></div><div class="learnItem"><span class="evidence ev-likely">LIKELY</span><strong>1:15 remains the best-supported working ICR. The 11 Sep review still does not show a repeated low pattern suggesting it is globally too strong.</strong></div><div class="learnItem"><span class="evidence ev-likely">LIKELY</span><strong>Meal composition, uncertain food and delayed high-fat effects explain more of the poorer excursions than a consistent global ICR problem.</strong></div><div class="learnItem"><span class="evidence ev-investigate">UNDER INVESTIGATION</span><strong>Rapid-starch and high-fat meals may eventually support their own personal timing patterns, but the evidence is not clean enough for a global timing rule.</strong></div><div class="learnItem"><span class="evidence ev-rule">ANALYSIS RULE</span><strong>Context-only untracked-food events are used to explain glucose but are excluded from clean ICR evidence.</strong></div><div class="learnItem"><span class="evidence ev-rule">ANALYSIS RULE</span><strong>Closely spaced foods are grouped before judging outcomes, and a newly logged meal is not judged until enough CGM follow-up exists.</strong></div></div></section>'''
s,n=learn_pattern.subn(learn,s,count=1)
if n!=1: raise SystemExit(f'learn replacement count {n}')

timeline_pattern=re.compile(r'<section class="card"><h2>Review timeline - last 5 uploads</h2>.*?</section>',re.S)
timeline='''<section class="card"><h2>Review timeline - last 5 uploads</h2><div class="timeline"><div class="review"><div class="reviewDate">11 Sep 2026</div><div class="reviewMetrics"><span class="chip">TIR 86%</span><span class="chip">Avg 7.6</span><span class="chip">GMI 6.6%</span><span class="chip">CV 30.0%</span></div></div><div class="review"><div class="reviewDate">8 Sep 2026</div><div class="reviewMetrics"><span class="chip">TIR 85%</span><span class="chip">Avg 7.6</span><span class="chip">GMI 6.6%</span><span class="chip">CV 30.4%</span></div></div><div class="review"><div class="reviewDate">6 Sep 2026</div><div class="reviewMetrics"><span class="chip">TIR 84%</span><span class="chip">Avg 7.7</span><span class="chip">GMI 6.6%</span><span class="chip">CV 29.9%</span></div></div><div class="review"><div class="reviewDate">2 Sep 2026</div><div class="reviewMetrics"><span class="chip">TIR 85%</span><span class="chip">Avg 7.7</span><span class="chip">GMI 6.6%</span><span class="chip">CV 28.8%</span></div></div><div class="review"><div class="reviewDate">29 Aug 2026</div><div class="reviewMetrics"><span class="chip">TIR 88%</span><span class="chip">Avg 7.5</span><span class="chip">GMI 6.5%</span><span class="chip">CV 27.1%</span></div></div></div></section>'''
s,n=timeline_pattern.subn(timeline,s,count=1)
if n!=1: raise SystemExit(f'timeline replacement count {n}')

marker='<div class="versionGrid">'
item='<div class="versionGrid"><div class="versionItem"><strong>11 Sep 2026 - CGM 3-file review</strong><ul><li>Updated CGM Progress to TIR 86%, average 7.6 mmol/L, GMI 6.6% and CV 30.0%.</li><li>Current 14-day window records 0% low and 0% very low.</li><li>1:15 remains the evidence-supported working ICR; context-only untracked food is excluded from clean ratio evidence.</li><li>No insulin calculation, correction-dose or CGM automation logic changed.</li></ul></div>'
if marker in s and '11 Sep 2026 - CGM 3-file review' not in s:
    s=s.replace(marker,item,1)
p.write_text(s,encoding='utf-8')

c=Path('CHANGELOG.md'); ct=c.read_text(encoding='utf-8')
entry='''# CGM review update - 11 Sep 2026\n\n- Processed the complete Dexcom Clarity PDF, raw Dexcom CSV and ICR Meal Dashboard CSV review set.\n- Updated CGM Progress to TIR 86%, average glucose 7.6 mmol/L, GMI 6.6% and CV 30.0%.\n- Current 14-day window records 0% low and 0% very low; all headline AGP goals remain achieved.\n- Kept 1:15 as the evidence-supported working ICR baseline.\n- Context-only untracked food, including the 10 Sep pub episode, is excluded from clean ICR evidence.\n- Added `reviews/CGM_REVIEW_2026-09-11.md`.\n- Rollback branch: `backup/pre-cgm-review-2026-09-11`.\n- No insulin calculation, correction-dose, Nightscout or clinical automation logic changed.\n\n'''
if not ct.startswith('# CGM review update - 11 Sep 2026'):
    c.write_text(entry+ct,encoding='utf-8')

b=Path('PROJECT_BRAIN.md'); bt=b.read_text(encoding='utf-8')
start=bt.index('## Current verified CGM baseline')
end=bt.index('\n## Important analysis rules',start)
new='''## Current verified CGM baseline\nLatest verified review is 11 Sep 2026 for 29 Aug-11 Sep 2026:\n- TIR 86%\n- Average glucose 7.6 mmol/L\n- GMI 6.6%\n- CV 30.0%\n- Very high 2%\n- High 12%\n- Low 0%\n- Very low 0%\n- CGM active 99.9%\n\nThe current evidence continues to support 1:15 as the working baseline. Context-only untracked food is excluded from clean ICR evidence, closely spaced eating is grouped, and high-fat/high-carb meals are assessed over the full delayed trace. Any insulin-setting change remains a discussion point for the diabetes team rather than an automatic app decision.\n'''
bt=bt[:start]+new+bt[end:]
b.write_text(bt,encoding='utf-8')
