from pathlib import Path
import re
p=Path('index.html');s=p.read_text(encoding='utf-8')
s=s.replace('ICR Meal Dashboard v2.10.1','ICR Meal Dashboard v2.10.2').replace('v2.10.1 LIVE','v2.10.2 LIVE')
pat=re.compile(r'<section class="card"><h2>My CGM progress</h2>.*?</section>\s*<section class="card"><h2>Clinical goals</h2>.*?</section>',re.S)
block='''<section class="card"><h2>My CGM progress</h2><div class="progressGrid"><div class="snapshot"><strong>Latest review - 4 Oct 2026</strong><div class="signalGrid" style="margin-top:10px"><div class="signal"><span>Time in range</span><strong>80.2%</strong></div><div class="signal"><span>Average glucose</span><strong>8.12</strong></div><div class="signal"><span>GMI</span><strong>6.81%</strong></div><div class="signal"><span>CV</span><strong>26.8%</strong></div></div><div class="reassure"><strong>Coach summary:</strong> The current Clarity window remains generally good but has slipped from the 27 Sep review because of more time above range. TIR is 80.2%, average glucose 8.12 mmol/L, GMI 6.81% and CV 26.8%. Time below 3.9 improved to 0.91% and below 3.0 to 0.18%; time above 10 increased to 18.94% and above 13.9 to 1.04%. The low burden has improved while variability remains excellent. <strong>ICR verdict:</strong> keep 1:15 as the evidence-supported working baseline for review with the diabetes team. The recent pattern does not justify a global tightening.</div></div><div><div class="learning good"><strong>What is working</strong><br>TIR remains above the 70% goal, GMI remains below 7% and CV is comfortably below 36%. Low exposure has improved compared with 27 Sep. Clean examples include the 1 Oct wrap and 3 Oct crumpets, which stayed below 10 mmol/L in their matched follow-up.</div><div class="learning watch"><strong>What to watch</strong><br>The main deterioration is more time high, concentrated around complex/high-fat or overlapping meals. Pasty showed a delayed rise from about 8.5 mmol/L at 2h to 13.7 at 4h. Chicking was about 8.9 at 2h and 8.0 at 4h before rising to about 12.3 at 6h. Cottage pie, PizzaExpress, pizza/chips/nuts and similar meals need full 4-6h interpretation rather than a simple 2h judgement.</div><div class="learning info"><strong>Data quality</strong><br>The app export now contains 113 meals plus 12 context events from 24 Aug to 4 Oct. The Clarity export contains 3,849 numeric CGM readings from 21 Sep to 4 Oct. Duplicate/overlapping food entries and context events are not treated as independent clean ICR evidence. Today's 4 Oct roast has insufficient follow-up in this Clarity export and is not yet judged.</div></div></div></section><section class="card"><h2>Clinical goals</h2><div class="goalGrid"><div class="goalItem"><div><strong>Time in range</strong><div class="goalMeta">Goal &gt;70% | Latest 80.2%</div></div><span class="tick">ACHIEVED</span></div><div class="goalItem"><div><strong>CV</strong><div class="goalMeta">Goal &lt;36% | Latest 26.8%</div></div><span class="tick">ACHIEVED</span></div><div class="goalItem"><div><strong>GMI</strong><div class="goalMeta">Goal &lt;7% | Latest 6.81%</div></div><span class="tick">ACHIEVED</span></div></div></section>'''
s,n=pat.subn(block,s,1);assert n==1
pat=re.compile(r'<section class="card"><h2>What I\'ve learned about Darren\'s diabetes</h2>.*?</section>',re.S)
block='''<section class="card"><h2>What I've learned about Darren's diabetes</h2><div class="learnGrid"><div class="learnItem"><span class="evidence ev-proven">PROVEN REPEATEDLY</span><strong>Overall TIR remains above goal and variability remains comfortably below target. The latest change is mainly more hyperglycaemia, not greater glucose instability.</strong></div><div class="learnItem"><span class="evidence ev-likely">LIKELY</span><strong>1:15 remains the best-supported working ICR. The current evidence does not show a repeated clean post-meal low pattern and does not justify tightening the ratio globally.</strong></div><div class="learnItem"><span class="evidence ev-proven">PROVEN REPEATEDLY</span><strong>High-fat and mixed meals can produce delayed glucose rises that are easy to miss at 2 hours. Pasty and Chicking are current clear examples, with poorer readings appearing at 4-6 hours.</strong></div><div class="learnItem"><span class="evidence ev-likely">LIKELY</span><strong>Meal composition and delayed post-Whipple absorption currently explain more of the difficult excursions than a single global ICR problem.</strong></div><div class="learnItem"><span class="evidence ev-investigate">UNDER INVESTIGATION</span><strong>Meal-specific bolus timing may matter, but the current evidence is not clean enough to set one pre-bolus rule for all foods.</strong></div><div class="learnItem"><span class="evidence ev-rule">ANALYSIS RULE</span><strong>Context events, missed insulin, duplicate/overlapping foods and meals without sufficient CGM follow-up are excluded from clean ICR conclusions.</strong></div></div></section>'''
s,n=pat.subn(block,s,1);assert n==1
pat=re.compile(r'<section class="card"><h2>Review timeline - last 5 uploads</h2>.*?</section>',re.S)
block='''<section class="card"><h2>Review timeline - last 5 uploads</h2><div class="timeline"><div class="review"><div class="reviewDate">4 Oct 2026</div><div class="reviewMetrics"><span class="chip">TIR 80.2%</span><span class="chip">Avg 8.12</span><span class="chip">GMI 6.81%</span><span class="chip">CV 26.8%</span></div></div><div class="review"><div class="reviewDate">27 Sep 2026</div><div class="reviewMetrics"><span class="chip">TIR 84.5%</span><span class="chip">Avg 7.78</span><span class="chip">GMI 6.66%</span><span class="chip">CV 27.1%</span></div></div><div class="review"><div class="reviewDate">11 Sep 2026</div><div class="reviewMetrics"><span class="chip">TIR 86%</span><span class="chip">Avg 7.6</span><span class="chip">GMI 6.6%</span><span class="chip">CV 30.0%</span></div></div><div class="review"><div class="reviewDate">8 Sep 2026</div><div class="reviewMetrics"><span class="chip">TIR 85%</span><span class="chip">Avg 7.6</span><span class="chip">GMI 6.6%</span><span class="chip">CV 30.4%</span></div></div><div class="review"><div class="reviewDate">6 Sep 2026</div><div class="reviewMetrics"><span class="chip">TIR 84%</span><span class="chip">Avg 7.7</span><span class="chip">GMI 6.6%</span><span class="chip">CV 29.9%</span></div></div></div></section>'''
s,n=pat.subn(block,s,1);assert n==1
marker='<div class="versionGrid">';item='''<div class="versionGrid"><div class="versionItem"><strong>v2.10.2 - 4 Oct 2026 CGM catch-up</strong><ul><li>Updated all CGM progress metrics and clinical goals from the 4 Oct Clarity export.</li><li>Recorded TIR 80.2%, average 8.12 mmol/L, GMI 6.81%, CV 26.8%, TBR &lt;3.9 0.91%, TBR &lt;3.0 0.18%, TAR &gt;10 18.94% and TAR &gt;13.9 1.04%.</li><li>Updated personalised observations to reflect improved low exposure but increased meal-related highs and delayed 4-6h rises.</li><li>Retained 1:15 as the current evidence-supported working ICR; no global tightening is supported by this review.</li><li>Updated data-quality counts to 113 meals, 12 context events and 3,849 numeric Clarity readings.</li><li>No insulin calculation, correction-dose, Nightscout or editable-meal-time logic changed.</li></ul></div>'''
if 'v2.10.2 - 4 Oct 2026 CGM catch-up' not in s:s=s.replace(marker,item,1)
p.write_text(s,encoding='utf-8')
